spring.application.name=SlackSDK

slack.board.add.url=http://localhost:8888/bo/board/add
slack.board.reply.delete.url=http://localhost:8888/bo/reply/delete
slack.board.reply.update.url=http://localhost:8888/bo/reply/update